/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/turbine-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/createTicket` | `/createTicket`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/searchTicket` | `/searchTicket`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/turbine-detail` | `/turbine-detail`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/turbine-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maintenance)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maintenance)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maintenance)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maintenance)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maintenance)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ptw)'}/createTicket` | `/createTicket`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ptw)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ptw)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ptw)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ptw)'}/searchTicket` | `/searchTicket`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ptw)'}/turbine-detail` | `/turbine-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/turbine-detail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(maintenance)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(maintenance)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(maintenance)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(maintenance)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(maintenance)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(ptw)'}/createTicket${`?${string}` | `#${string}` | ''}` | `/createTicket${`?${string}` | `#${string}` | ''}` | `${'/(ptw)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(ptw)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(ptw)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(ptw)'}/searchTicket${`?${string}` | `#${string}` | ''}` | `/searchTicket${`?${string}` | `#${string}` | ''}` | `${'/(ptw)'}/turbine-detail${`?${string}` | `#${string}` | ''}` | `/turbine-detail${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/turbine-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maintenance)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/createTicket` | `/createTicket`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/searchTicket` | `/searchTicket`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ptw)'}/turbine-detail` | `/turbine-detail`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; };
    }
  }
}
