import {
  MOCK_SPRINT_DATA,
} from '../../../../utils/mockData';
import type { Ticket } from '../types/sprintData.types';

// Re-export for Dashboard
export { MOCK_SPRINT_DATA };

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 1,
    team: 'Frontend',
    assignee: 'Aarav Sharma',
    issueType: 'Story',
    issueNo: 'SCRUM-101',
    summary: 'Login form validation and error handling',
    timeLoggingId: 'TL-001',
    status: 'In Progress',
    storyPoints: 5,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-10',
    workEndDate: '2026-06-13',
    ticketLink: 'https://jira.example.com/browse/SCRUM-101',
  },
  {
    id: 2,
    team: 'Backend',
    assignee: 'Priya Iyer',
    issueType: 'Task',
    issueNo: 'SCRUM-102',
    summary: 'Refactor auth middleware to support refresh tokens',
    timeLoggingId: 'TL-002',
    status: 'In Review',
    storyPoints: 8,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-08',
    workEndDate: '2026-06-12',
    ticketLink: 'https://jira.example.com/browse/SCRUM-102',
  },
  {
    id: 3,
    team: 'QA',
    assignee: 'Rahul Verma',
    issueType: 'Bug',
    issueNo: 'SCRUM-103',
    summary: 'Dashboard chart fails to load on Safari 17',
    timeLoggingId: 'TL-003',
    status: 'Blocked',
    storyPoints: 3,
    fixVersion: 'v2.3.2',
    carryForward: 'Sprint 22',
    carryForwardReason:
      'Carried forward from Sprint 22 — blocked on Safari 17 WebKit fix from upstream; deferred to unblock QA verification.',
    workStartDate: '2026-06-05',
    workEndDate: '2026-06-09',
    ticketLink: 'https://jira.example.com/browse/SCRUM-103',
  },
  {
    id: 4,
    team: 'DevOps',
    assignee: 'Sneha Kapoor',
    issueType: 'Task',
    issueNo: 'SCRUM-104',
    summary: 'Set up staging environment with PostgreSQL 16',
    timeLoggingId: 'TL-004',
    status: 'Done',
    storyPoints: 5,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-01',
    workEndDate: '2026-06-03',
    ticketLink: 'https://jira.example.com/browse/SCRUM-104',
  },
  {
    id: 5,
    team: 'Frontend',
    assignee: 'Manoj Patel',
    issueType: 'Story',
    issueNo: 'SCRUM-105',
    summary: 'Build ticket overview table on Dashboard',
    timeLoggingId: 'TL-005',
    status: 'In Progress',
    storyPoints: 8,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-09',
    workEndDate: '2026-06-15',
    ticketLink: 'https://jira.example.com/browse/SCRUM-105',
  },
  {
    id: 6,
    team: 'Backend',
    assignee: 'Karthik Reddy',
    issueType: 'Story',
    issueNo: 'SCRUM-106',
    summary: 'Add WebSocket support for live sprint updates',
    timeLoggingId: 'TL-006',
    status: 'In Test',
    storyPoints: 13,
    fixVersion: 'v2.5.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-05-28',
    workEndDate: '2026-06-06',
    ticketLink: 'https://jira.example.com/browse/SCRUM-106',
  },
  {
    id: 7,
    team: 'QA',
    assignee: 'Neha Gupta',
    issueType: 'Task',
    issueNo: 'SCRUM-107',
    summary: 'Automate regression suite for sprint 23',
    timeLoggingId: 'TL-007',
    status: 'To Do',
    storyPoints: 5,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-15',
    workEndDate: '2026-06-19',
    ticketLink: 'https://jira.example.com/browse/SCRUM-107',
  },
  {
    id: 8,
    team: 'Frontend',
    assignee: 'Rohan Mehta',
    issueType: 'Bug',
    issueNo: 'SCRUM-108',
    summary: 'Date picker not respecting user timezone',
    timeLoggingId: 'TL-008',
    status: 'In Review',
    storyPoints: 2,
    fixVersion: 'v2.3.2',
    carryForward: 'Sprint 23',
    carryForwardReason:
      'Carried forward from Sprint 23 — needs a follow-up to cover DST edge cases after the initial fix.',
    workStartDate: '2026-06-04',
    workEndDate: '2026-06-05',
    ticketLink: 'https://jira.example.com/browse/SCRUM-108',
  },
  {
    id: 9,
    team: 'Design',
    assignee: 'Anika Joshi',
    issueType: 'Task',
    issueNo: 'SCRUM-109',
    summary: 'Design empty states for ticket list and reports',
    timeLoggingId: 'TL-009',
    status: 'Done',
    storyPoints: 3,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-05-30',
    workEndDate: '2026-06-01',
    ticketLink: 'https://jira.example.com/browse/SCRUM-109',
  },
  {
    id: 10,
    team: 'Backend',
    assignee: 'Vikram Singh',
    issueType: 'Story',
    issueNo: 'SCRUM-110',
    summary: 'Implement RBAC for admin operations',
    timeLoggingId: 'TL-010',
    status: 'In Progress',
    storyPoints: 13,
    fixVersion: 'v2.5.0',
    carryForward: 'Sprint 22',
    carryForwardReason:
      'Carried forward from Sprint 22 — scope grew to include the audit-log requirement after security review.',
    workStartDate: '2026-06-02',
    workEndDate: '2026-06-12',
    ticketLink: 'https://jira.example.com/browse/SCRUM-110',
  },
  {
    id: 11,
    team: 'DevOps',
    assignee: 'Ishaan Khanna',
    issueType: 'Bug',
    issueNo: 'SCRUM-111',
    summary: 'CI pipeline flaky on integration test stage',
    timeLoggingId: 'TL-011',
    status: 'Blocked',
    storyPoints: 3,
    fixVersion: 'v2.4.0',
    carryForward: 'Sprint 21',
    carryForwardReason:
      'Carried forward from Sprint 21 — needs a runner image upgrade from infra team to stabilize the integration stage.',
    workStartDate: '2026-06-06',
    workEndDate: '2026-06-10',
    ticketLink: 'https://jira.example.com/browse/SCRUM-111',
  },
  {
    id: 12,
    team: 'Frontend',
    assignee: 'Aarav Sharma',
    issueType: 'Task',
    issueNo: 'SCRUM-112',
    summary: 'Add dark mode toggle in user settings',
    timeLoggingId: 'TL-012',
    status: 'To Do',
    storyPoints: 5,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-16',
    workEndDate: '2026-06-19',
    ticketLink: 'https://jira.example.com/browse/SCRUM-112',
  },
  {
    id: 13,
    team: 'QA',
    assignee: 'Priya Iyer',
    issueType: 'Spike',
    issueNo: 'SCRUM-113',
    summary: 'Investigate Playwright vs Cypress for E2E tests',
    timeLoggingId: 'TL-013',
    status: 'Done',
    storyPoints: 2,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-05-25',
    workEndDate: '2026-05-26',
    ticketLink: 'https://jira.example.com/browse/SCRUM-113',
  },
  {
    id: 14,
    team: 'Frontend',
    assignee: 'Rohan Mehta',
    issueType: 'Spike',
    issueNo: 'SCRUM-114a',
    summary: 'Research WebSocket vs SSE for live dashboard updates',
    timeLoggingId: 'TL-014a',
    status: 'In Progress',
    storyPoints: 3,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-08',
    workEndDate: '2026-06-12',
    ticketLink: 'https://jira.example.com/browse/SCRUM-114a',
  },
  {
    id: 15,
    team: 'Backend',
    assignee: 'Karthik Reddy',
    issueType: 'Spike',
    issueNo: 'SCRUM-115a',
    summary: 'Evaluate PostgreSQL 16 partitioning for telemetry table',
    timeLoggingId: 'TL-015a',
    status: 'In Review',
    storyPoints: 5,
    fixVersion: 'v2.5.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-04',
    workEndDate: '2026-06-09',
    ticketLink: 'https://jira.example.com/browse/SCRUM-115a',
  },
  {
    id: 16,
    team: 'Backend',
    assignee: 'Sneha Kapoor',
    issueType: 'Task',
    issueNo: 'SCRUM-114',
    summary: 'Optimize slow query on sprint burndown table',
    timeLoggingId: 'TL-014',
    status: 'In Test',
    storyPoints: 5,
    fixVersion: 'v2.4.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-03',
    workEndDate: '2026-06-07',
    ticketLink: 'https://jira.example.com/browse/SCRUM-114',
  },
  {
    id: 17,
    team: 'Frontend',
    assignee: 'Manoj Patel',
    issueType: 'Bug',
    issueNo: 'SCRUM-115',
    summary: 'Tooltip clipped on small viewport in incentive report',
    timeLoggingId: 'TL-015',
    status: 'In Review',
    storyPoints: 2,
    fixVersion: 'v2.3.2',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-11',
    workEndDate: '2026-06-12',
    ticketLink: 'https://jira.example.com/browse/SCRUM-115',
  },
  {
    id: 18,
    team: 'Design',
    assignee: 'Anika Joshi',
    issueType: 'Story',
    issueNo: 'SCRUM-116',
    summary: 'Refresh design system with new color tokens',
    timeLoggingId: 'TL-016',
    status: 'In Progress',
    storyPoints: 8,
    fixVersion: 'v2.5.0',
    carryForward: '',
    carryForwardReason: '',
    workStartDate: '2026-06-04',
    workEndDate: '2026-06-13',
    ticketLink: 'https://jira.example.com/browse/SCRUM-116',
  },
];
