/**
 * WhatsApp Service for sending reports
 * Uses free WhatsApp Business API (360dialog partner)
 * This is a structured service that can be easily connected to real WhatsApp APIs
 * Uses native fetch API (available in Node.js 18+)
 */

// WhatsApp API Configuration
// For production, use environment variables and secure credential storage
const WHATSAPP_CONFIG = {
  // 360dialog WhatsApp API (Partner with Meta) - Free tier available
  // Get your credentials from: https://hub.360dialog.com/
  baseUrl: process.env.WHATSAPP_API_URL || 'https://api.360dialog.com/v1',
  apiKey: process.env.WHATSAPP_API_KEY || '',
  phoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID || '',
  templateNamespace: process.env.WHATSAPP_TEMPLATE_NAMESPACE || '',
};

export interface WhatsAppMessage {
  to: string;
  templateName: string;
  language?: string;
  components?: {
    type: 'header' | 'body' | 'footer' | 'buttons';
    parameters: { type: string; text?: string; image?: { link: string } }[];
  }[];
}

export interface ReportMessage {
  recipient: string;
  reportType: string;
  reportData: {
    title: string;
    dateRange: string;
    summary: string;
    keyMetrics: { label: string; value: string }[];
    sprints: string[];
  };
}

export interface ScheduledReport {
  id: string;
  reportType: string;
  recipient: string;
  frequency: 'hourly' | 'daily' | 'weekly';
  enabled: boolean;
  lastSent?: Date;
  nextScheduled?: Date;
}

class WhatsAppService {
  private apiKey: string;
  private phoneNumberId: string;
  private baseUrl: string;

  constructor() {
    this.apiKey = WHATSAPP_CONFIG.apiKey;
    this.phoneNumberId = WHATSAPP_CONFIG.phoneNumberId;
    this.baseUrl = WHATSAPP_CONFIG.baseUrl;
  }

  /**
   * Check if WhatsApp is configured
   */
  isConfigured(): boolean {
    return !!(this.apiKey && this.phoneNumberId);
  }

  /**
   * Format phone number to WhatsApp format (country code + number)
   */
  private formatPhoneNumber(phone: string): string {
    // Remove all non-digits
    const digits = phone.replace(/\D/g, '');

    // Add country code if not present (assuming India +91)
    if (digits.length === 10) {
      return `91${digits}`;
    }
    return digits;
  }

  /**
   * Send a text message via WhatsApp (using native fetch)
   */
  async sendMessage(
    to: string,
    message: string,
  ): Promise<{ success: boolean; messageId?: string; error?: string }> {
    if (!this.isConfigured()) {
      console.log(
        '[WhatsApp] Service not configured - message would be sent to:',
        this.formatPhoneNumber(to),
      );
      console.log('[WhatsApp] Message:', message);
      // Return mock success for demo purposes
      return {
        success: true,
        messageId: `mock-${Date.now()}`,
        error: undefined,
      };
    }

    try {
      const formattedPhone = this.formatPhoneNumber(to);

      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messaging_product: 'whatsapp',
          to: formattedPhone,
          type: 'text',
          text: { body: message },
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        return {
          success: false,
          error: data.error?.message || 'Failed to send message',
        };
      }

      return {
        success: true,
        messageId: data.messages?.[0]?.id,
      };
    } catch (error: any) {
      console.error('[WhatsApp] Send error:', error.message);
      return {
        success: false,
        error: error.message,
      };
    }
  }

  /**
   * Send a formatted report message
   */
  async sendReport(
    report: ReportMessage,
  ): Promise<{ success: boolean; messageId?: string; error?: string }> {
    const message = this.formatReportMessage(report);
    return this.sendMessage(report.recipient, message);
  }

  /**
   * Format report data into a readable WhatsApp message
   */
  private formatReportMessage(report: ReportMessage): string {
    const { reportData } = report;

    let message = `📊 *SPRINTPULSE REPORT*\n`;
    message += `━━━━━━━━━━━━━━━━━━━━\n\n`;
    message += `📋 *${reportData.title}*\n`;
    message += `📅 ${reportData.dateRange}\n\n`;

    if (reportData.keyMetrics.length > 0) {
      message += `*Key Metrics:*\n`;
      reportData.keyMetrics.forEach((metric) => {
        message += `• ${metric.label}: *${metric.value}*\n`;
      });
      message += `\n`;
    }

    message += `🏃 *Sprints:* ${reportData.sprints.join(', ')}\n`;
    message += `━━━━━━━━━━━━━━━━━━━━\n\n`;
    message += `📝 *Summary:*\n${reportData.summary}\n\n`;
    message += `🔗 Generated by SprintPulse Platform\n`;
    message += `🕐 ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`;

    return message;
  }

  /**
   * Send hourly report summary
   */
  async sendHourlyReport(
    recipient: string,
    reportType: string,
    kpiData: any[],
    downtimeData: any[],
    sprintIds: string[],
  ): Promise<{ success: boolean; messageId?: string; error?: string }> {
    const totalPoints = kpiData
      .filter((row) => row.kpi?.includes('Story Points'))
      .reduce((sum, row) => {
        const { total } = row;
        return sum + (parseFloat(total) || 0);
      }, 0);

    const avgProgress = kpiData
      .filter((row) => row.kpi?.includes('Progress'))
      .reduce((sum, row, _, arr) => {
        const val = parseFloat(row.total);
        return sum + (isNaN(val) ? 0 : val) / arr.length;
      }, 0);

    const downtimeCount = downtimeData.length;
    const activeSprints = sprintIds.length;

    const report: ReportMessage = {
      recipient,
      reportType,
      reportData: {
        title: `${reportType} - Hourly Update`,
        dateRange: `${new Date().toLocaleDateString('en-GB')} | ${new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`,
        summary: `Hourly sprint report for ${activeSprints} sprints. ${downtimeCount} blocker events recorded.`,
        keyMetrics: [
          { label: 'Story Points Completed', value: `${totalPoints.toFixed(2)} pts` },
          { label: 'Avg Sprint Progress', value: `${avgProgress.toFixed(2)}%` },
          { label: 'Active Sprints', value: `${activeSprints}` },
          { label: 'Blocker Events', value: `${downtimeCount}` },
        ],
        sprints: sprintIds.map((s) => s.toUpperCase()),
      },
    };

    return this.sendReport(report);
  }

  /**
   * Send daily summary report
   */
  async sendDailyReport(
    recipient: string,
    reportData: {
      date: string;
      totalGeneration: string;
      avgAvailability: string;
      maxVelocity: string;
      scheduledDowntime: string;
      unscheduledDowntime: string;
      sprints: string[];
    },
  ): Promise<{ success: boolean; messageId?: string; error?: string }> {
    const report: ReportMessage = {
      recipient,
      reportType: 'Daily Sprint Report',
      reportData: {
        title: 'Daily Sprint Summary',
        dateRange: reportData.date,
        summary: `Daily report for ${reportData.sprints.length} sprints with ${reportData.scheduledDowntime} scheduled and ${reportData.unscheduledDowntime} unscheduled blockers.`,
        keyMetrics: [
          { label: 'Story Points Completed', value: reportData.totalGeneration },
          { label: 'Avg Sprint Progress', value: reportData.avgAvailability },
          { label: 'Max Velocity', value: reportData.maxVelocity },
          { label: 'Scheduled Blockers', value: reportData.scheduledDowntime },
          { label: 'Unscheduled Blockers', value: reportData.unscheduledDowntime },
        ],
        sprints: reportData.sprints,
      },
    };

    return this.sendReport(report);
  }

  /**
   * Send PDF/Excel report as document
   */
  async sendReportDocument(
    to: string,
    documentUrl: string,
    caption: string,
  ): Promise<{ success: boolean; messageId?: string; error?: string }> {
    if (!this.isConfigured()) {
      console.log('[WhatsApp] Document would be sent to:', this.formatPhoneNumber(to));
      console.log('[WhatsApp] Document URL:', documentUrl);
      console.log('[WhatsApp] Caption:', caption);
      return { success: true, messageId: `mock-doc-${Date.now()}` };
    }

    try {
      const formattedPhone = this.formatPhoneNumber(to);

      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messaging_product: 'whatsapp',
          to: formattedPhone,
          type: 'document',
          document: {
            link: documentUrl,
            caption,
          },
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        return { success: false, error: data.error?.message || 'Failed to send document' };
      }

      return {
        success: true,
        messageId: data.messages?.[0]?.id,
      };
    } catch (error: any) {
      return {
        success: false,
        error: error.message,
      };
    }
  }

  /**
   * Get message delivery status
   */
  async getMessageStatus(
    messageId: string,
  ): Promise<{ status: string; timestamp?: string } | null> {
    if (!this.isConfigured()) {
      return { status: 'delivered', timestamp: new Date().toISOString() };
    }

    try {
      const response = await fetch(`${this.baseUrl}/messages/${messageId}`, {
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json',
        },
      });

      const data = await response.json();

      return {
        status: data.status,
        timestamp: data.timestamp,
      };
    } catch (error) {
      return null;
    }
  }
}

// Singleton instance
export const whatsAppService = new WhatsAppService();

// Export class for testing
export default WhatsAppService;
